Remove the additional function context on DOMContentLoaded
babel/babel-standalone pull request #97
Opened 2017-12-22 17:32 UTC by stevefan1999

https://github.com/babel/babel-standalone/blob/master/src/index.js#L260

https://github.com/babel/babel-standalone/blob/master/src/index.js#L275

This is so wrong. No wonder I cannot remove the listener because the reference is different.

2017-12-22 17:58 UTC, Daniel15 requested changes
Please test your changes. This will not actually work as it will pass the event argument to `transformScriptTags` which breaks it. `transformScriptTags` must take **no** arguments in the DOMContentLoaded case.

Also, please submit this to the main Babel repo rather than this repo. This repo is no longer used.

2017-12-22 18:07 UTC, stevefan1999 commented
@Daniel15 Thanks for the answer, this fat arrow confused me for so long.

One possible workaround: extract that as a function then re-associate the handler. This will still keep the handler reference so for removeEventListener to get rid of it.

2017-12-22 18:16 UTC, Daniel15 commented
Sure, that'd work. The other thing you could do is assign it to a variable:
```
const transformOnLoad = () => transformScriptTags();

window.addEventListener('DOMContentLoaded', transformOnLoad, false); 

window.removeEventListener('DOMContentLoaded', transformOnLoad); 
```

2017-12-22 18:17 UTC, Daniel15 commented
Sure, that'd work.

2017-12-23 01:58 UTC, stevefan1999 commented
Closing this as the main PR is 'merged' in the monorepo

2017-12-23 01:58 UTC, closed without merging